Repository boostcampth/boostcamp3_G, pull requests merged in 2019-01, with the labels that each got.

#4 프로젝트 경로 변경
  .gitignore
  app/.gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/androidTest/java/com/boostcamp/dreampicker/ExampleInstrumentedTest.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/MainActivity.java
  app/src/main/res/drawable-v24/ic_launcher_foreground.xml
  app/src/main/res/drawable/ic_launcher_background.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher.xml
  app/src/main/res/mipmap-anydpi-v26/ic_launcher_round.xml
  app/src/main/res/mipmap-hdpi/ic_launcher.png
  app/src/main/res/mipmap-hdpi/ic_launcher_round.png
  app/src/main/res/mipmap-mdpi/ic_launcher.png
  app/src/main/res/mipmap-mdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xhdpi/ic_launcher.png
  app/src/main/res/mipmap-xhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxhdpi/ic_launcher_round.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher.png
  app/src/main/res/mipmap-xxxhdpi/ic_launcher_round.png
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/boostcamp/dreampicker/ExampleUnitTest.java
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
  settings.gradle
Labels: 이거머지

#5 이슈, PR 템플릿 추가
  .github/ISSUE_TEMPLATE.md
  .github/PULL_REQUEST_TEMPLATE.md
Labels: 이거머지

#8 Readme 추가
  README.md
Labels: 리뷰해주세요, 슈퍼심플

#19 메인공통 - 각 화면으로 전환
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/model/TempModel.java
  app/src/main/java/com/boostcamp/dreampicker/view/BaseActivity.java
  app/src/main/java/com/boostcamp/dreampicker/view/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/MyPageFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/ResultFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/SearchFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/UpLoadFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/main/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/BaseVIewModel.java
  app/src/main/res/drawable/ic_dashboard_black_24dp.xml
  app/src/main/res/drawable/ic_home_24dp.xml
  app/src/main/res/drawable/ic_home_black_24dp.xml
  app/src/main/res/drawable/ic_home_gray_24dp.xml
  app/src/main/res/drawable/ic_my_page_24dp.xml
  app/src/main/res/drawable/ic_my_page_gray_24dp.xml
  app/src/main/res/drawable/ic_notifications_black_24dp.xml
  app/src/main/res/drawable/ic_result_24dp.xml
  app/src/main/res/drawable/ic_result_gray_24dp.xml
  app/src/main/res/drawable/ic_search_24dp.xml
  app/src/main/res/drawable/ic_search_gray_24dp.xml
  app/src/main/res/drawable/ic_up_load_24dp.xml
  app/src/main/res/drawable/ic_up_load_gray_24dp.xml
  app/src/main/res/drawable/img_logo.png
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/fragment_my_page.xml
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_search.xml
  app/src/main/res/layout/fragment_up_load.xml
  app/src/main/res/menu/navigation.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
Labels: 답변주세요

#26 리소스 수정
  app/src/main/res/drawable/btn_home_normal.xml
  app/src/main/res/drawable/btn_home_selected.xml
  app/src/main/res/drawable/btn_my_page_normal.xml
  app/src/main/res/drawable/btn_my_page_selected.xml
  app/src/main/res/drawable/btn_result_normal.xml
  app/src/main/res/drawable/btn_result_selected.xml
  app/src/main/res/drawable/btn_search_normal.xml
  app/src/main/res/drawable/btn_search_selected.xml
  app/src/main/res/drawable/btn_up_load_normal.xml
  app/src/main/res/drawable/btn_up_load_selected.xml
  app/src/main/res/menu/navigation.xml
Labels: 슈퍼심플, 이거머지

#24 스플래시 화면(액티비티) 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/view/SplashActivity.java
  app/src/main/res/layout/activity_splash.xml
  app/src/main/res/values/dimens.xml
Labels: 슈퍼심플, 이거머지

#23 로그인 - 화면(액티비티) 전환
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/view/LogInActivity.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/BaseViewModel.java
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/values/dimens.xml
Labels: 슈퍼심플, 이거머지

#27 메인피드 - 피드 출력
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/view/feed/Feed.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/Image.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/User.java
  app/src/main/java/com/boostcamp/dreampicker/view/main/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/BaseViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/FeedViewModel.java
  app/src/main/res/drawable/ic_box.xml
  app/src/main/res/drawable/image1.jpg
  app/src/main/res/drawable/image2.jpg
  app/src/main/res/drawable/jajang.jpg
  app/src/main/res/drawable/jambong.jpg
  app/src/main/res/drawable/profile.jpg
  app/src/main/res/drawable/profile2.jpg
  app/src/main/res/drawable/profile3.jpg
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
Labels: 리뷰해주세요

#32 메인피드 - 데이터바인딩을 사용한 구현
  app/src/main/java/com/boostcamp/dreampicker/model/Feed.java
  app/src/main/java/com/boostcamp/dreampicker/model/Image.java
  app/src/main/java/com/boostcamp/dreampicker/model/TempModel.java
  app/src/main/java/com/boostcamp/dreampicker/model/User.java
  app/src/main/java/com/boostcamp/dreampicker/model/source/feed/FeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/model/source/feed/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/model/source/user/UserRepository.java
  app/src/main/java/com/boostcamp/dreampicker/view/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/view/feed/Image.java
  app/src/main/java/com/boostcamp/dreampicker/view/main/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/BaseViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/FeedViewModel.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/layout_feed_photo_tag.xml
  app/src/main/res/values/dimens.xml
Labels: 리뷰해주세요

#38 BaseViewModel 최적화
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/BaseViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/FeedViewModel.java
Labels: 리뷰해주세요, 슈퍼심플

#44 공통으로 사용되는 프래그먼트 붙이기 위한 FrameActivity 생성
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/view/feedDetail/FeedDetailFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/feedList/FeedListAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/view/feedList/FeedListFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/main/FrameActivity.java
  app/src/main/java/com/boostcamp/dreampicker/view/search/SearchFragment.java
  app/src/main/res/layout/activity_frame.xml
  app/src/main/res/layout/fragment_feed_detail.xml
  app/src/main/res/layout/item_feed_list.xml
Labels: 리뷰해주세요

#51 유저 리스트 뷰 생성
  app/src/main/java/com/boostcamp/dreampicker/data/source/feed/FeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/feed/FeedRemoteDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/feed/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/user/UserDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/user/UserRemoteDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/user/UserRepository.java
  app/src/main/java/com/boostcamp/dreampicker/view/feedList/FeedListFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/main/FrameActivity.java
  app/src/main/java/com/boostcamp/dreampicker/view/profile/ProfileFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/search/SearchFragment.java
  app/src/main/java/com/boostcamp/dreampicker/view/userList/UserListAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/view/userList/UserListFragment.java
  app/src/main/res/layout/fragment_profile.xml
  app/src/main/res/layout/fragment_user_list.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_user_list.xml
  app/src/main/res/layout/layout_profile_count.xml
  app/src/main/res/values/dimens.xml
Labels: 리뷰해주세요

#52 파이어베이스 - 메인 피드 데이터 가져오기
  .gitignore
  app/build.gradle
  app/google-services.json
  app/src/main/java/com/boostcamp/dreampicker/data/source/feed/FeedRemoteDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/feed/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/user/UserRemoteDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/model/Feed.java
  app/src/main/java/com/boostcamp/dreampicker/model/Image.java
  app/src/main/java/com/boostcamp/dreampicker/model/User.java
  app/src/main/java/com/boostcamp/dreampicker/model/UserInfo.java
  app/src/main/java/com/boostcamp/dreampicker/viewmodel/FeedViewModel.java
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_list.xml
  build.gradle
Labels: 이거머지
