Repository boostcampth/boostcamp3_G, pull requests merged in 2019-02, with the labels that each got.

#80 투표 이미지, 카메라 등록하기
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/view/upload/UploadActivity.java
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/activity_upload_detail_left.xml
  app/src/main/res/layout/activity_upload_detail_right.xml
  app/src/main/res/values/dimens.xml
Labels: 리뷰해주세요

#87 테스트용 MockDataSource 추가
  app/src/main/java/com/boostcamp/dreampicker/data/source/FeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/UserDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/FeedMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/UserMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/FeedFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/UserFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/repository/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/repository/UserRepository.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/detail/FeedDetailFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/detail/FeedDetailViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/list/FeedListAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/list/FeedListFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/list/FeedListViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModelFactory.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/FrameActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/notification/NotificationFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/SearchFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/user/list/UserListAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/user/list/UserListFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/user/list/UserListViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/user/profile/ProfileFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/user/profile/ProfileViewModel.java
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
Labels: 리뷰해주세요, 슈퍼심플

#88 리드미 업데이트
  README.md
Labels: 슈퍼심플

#89 뷰모델 최적화, 리스트 어댑터 적용
  app/src/main/java/com/boostcamp/dreampicker/data/model/Feed.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/BaseViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewHolder.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModelFactory.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/VoteResult.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/listener/OnDropListener.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/listener/VoteContainerDragListener.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/listener/VoteDragListener.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/listener/VoteIconTouchListener.java
  app/src/main/java/com/boostcamp/dreampicker/utils/AnimationUtil.java
  app/src/main/java/com/boostcamp/dreampicker/utils/BindingUtil.java
  app/src/main/java/com/boostcamp/dreampicker/utils/ImageUtil.java
  app/src/main/res/layout/fragment_feed.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_vote_left.xml
  app/src/main/res/layout/item_feed_vote_right.xml
Labels: 리뷰해주세요

#91 파이어베이스 데이터소스 구현
  app/src/main/java/com/boostcamp/dreampicker/data/model/Feed.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/FeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/FeedMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/FeedFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/UserFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/repository/FeedRepository.java
  build.gradle
Labels: 리뷰해주세요

#92 업로드 뷰모델 추가
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/data/model/Image.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/utils/ImageUtil.java
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/activity_upload_detail_left.xml
  app/src/main/res/layout/activity_upload_detail_right.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
Labels: 리뷰해주세요

#94 업로드 - 투표 생성 처리
  app/src/main/java/com/boostcamp/dreampicker/data/model/Image.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/utils/BindingUtil.java
  app/src/main/res/drawable/btn_toolbar_check.xml
  app/src/main/res/drawable/btn_toolbar_close.xml
  app/src/main/res/drawable/btn_toolbar_finger.png
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/layout/layout_toolbar.xml
Labels: 리뷰해주세요

#97 메인피드 - 태그 리스트로 표현
  app/src/main/java/com/boostcamp/dreampicker/data/model/Image.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/FeedMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/listener/VoteIconTouchListener.java
  app/src/main/java/com/boostcamp/dreampicker/utils/BindingUtil.java
  app/src/main/res/drawable/ic_box.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_feed_vote_left.xml
  app/src/main/res/layout/item_feed_vote_right.xml
  app/src/main/res/values/dimens.xml
Labels: 리뷰해주세요

#98 로그인 - 로그인 기능 구현
  .gitignore
  app/build.gradle
  app/proguard-rules.pro
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/LogInActivity.java
  app/src/main/res/layout/activity_log_in.xml
  app/src/main/res/values/dimens.xml
Labels: 리뷰해주세요

#122 파이어베이스 - 업로드 피드
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/data/source/FeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/MyProfileDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/UploadDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/UserDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/FeedMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/ProfileMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/UploadMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/UserMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/FeedFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/UserFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/repository/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/repository/UserRepository.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModelFactory.java
  app/src/main/res/layout/fragment_feed_detail_left.xml
  app/src/main/res/layout/fragment_feed_detail_right.xml
Labels: 리뷰해주세요

#124 pagedDataSource disposable 제거
  app/build.gradle
  app/src/main/java/com/boostcamp/dreampicker/presentation/BaseViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFeedPagedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFeedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/feed/SearchFeedPagedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/feed/SearchFeedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/user/SearchUserPagedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/user/SearchUserViewModel.java
Labels: 리뷰해주세요, 슈퍼심플

#126 회원가입, 프로필 - 실서버연동
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/data/model/UserDetail.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/UserDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/FeedMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/UserMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/UserFirebaseService.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/request/InsertUserRequest.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/remote/firebase/response/ProfileUserDetailResponse.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/repository/UserRepository.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/LogInActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFeedPagedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/utils/FirebaseManager.java
  app/src/main/res/layout/fragment_profile.xml
Labels: 이거머지

#136 피드검색 실서버 연동
  app/src/main/java/com/boostcamp/dreampicker/data/paging/datasource/SearchFeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/paging/repository/SearchFeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/local/test/FeedMockDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/SearchFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/search/feed/SearchFeedViewModel.java
Labels: 리뷰해주세요

#169 issue-152 업로드 뷰 구현
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firebase/model/FeedItemRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firebase/model/FeedRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firebase/model/mapper/FeedRequestMapper.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/LegacyUploadViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModelFactory.java
  app/src/main/java/com/boostcamp/dreampicker/utils/BindingUtil.java
  app/src/main/java/com/boostcamp/dreampicker/utils/ImageUtil.java
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/values/strings.xml
Labels: 답변주세요

#171 issue-170 업로드 쿼리 수정
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firebase/model/MyFeedRemoteData.java
Labels: 슈퍼심플

#177 ISSUE-176 업로드 부가기능 구현
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firestore/model/MyFeedRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/databinding/ImageUtil.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/values/strings.xml
Labels: 리뷰해주세요

#181 Issue-173 Toolbar 추가
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/MainActivity.java
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/layout/fragment_feed.xml
Labels: 리뷰해주세요, 슈퍼심플

#192 투표 마감 repository 설계 및 구현
  app/src/main/java/com/boostcamp/dreampicker/data/repository/UserRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/repository/UserRepositoryImpl.java
Labels: 리뷰해주세요

#195 issue-188 상세보기 데이터클래스 설계
  app/src/main/java/com/boostcamp/dreampicker/data/model/FeedDetail.java
Labels: 리뷰해주세요, 슈퍼심플

#194 isuue-178 업로드 쿼리 수정
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firestore/mapper/FeedRequestMapper.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firestore/model/FeedRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firestore/model/MyFeedRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/res/layout/activity_upload.xml
Labels: 리뷰해주세요

#198 isuue 189 상세보기 인터페이스 설계 및 구현
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/data/source/firestore/mapper/FeedResponseMapper.java
  app/src/main/res/layout/activity_upload.xml
Labels: 리뷰해주세요

#206 Issue-204 결과 보기 - View 구현 완료
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepository.java
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/voted/VotedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/voted/VotedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/voted/VotedViewHolder.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/voted/VotedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/voted/VotedViewModelFactory.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/MainActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/result/ResultFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/result/ResultViewModelFactory.java
  app/src/main/res/layout/fragment_result.xml
  app/src/main/res/layout/fragment_voted.xml
  app/src/main/res/layout/item_feed.xml
  app/src/main/res/layout/item_voted_feed.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings.xml
Labels: 리뷰해주세요

#210 issue-209 크래시리틱스 적용
  app/build.gradle
  app/src/main/AndroidManifest.xml
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: 리뷰해주세요, 슈퍼심플

#213 [Issue-212] 업로드 태그 미반영 수정
  app/src/main/java/com/boostcamp/dreampicker/extension/common/StringExt.java
  app/src/main/java/com/boostcamp/dreampicker/extension/databinding/BindingUtil.java
  app/src/main/java/com/boostcamp/dreampicker/extension/databinding/ImageUtil.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/SplashActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
Labels: 리뷰해주세요, 슈퍼심플

#222 [Issue-221] 태그리스트 미반영 버그 수정
  app/src/main/java/com/boostcamp/dreampicker/extension/databinding/BindingUtil.java
Labels: 슈퍼심플

#230 issue-229 프로필 에러수정
  app/src/main/java/com/boostcamp/dreampicker/data/paging/MyFeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFragment.java
Labels: 리뷰해주세요, 슈퍼심플

#232 [Issue-226] 상세보기 -> 메인 피드 onActivityResult 구현
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/detail/FeedDetailActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewHolder.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModel.java
  app/src/main/res/values/strings.xml
Labels: 리뷰해주세요, 슈퍼심플

#242 issue-239 Leakcanary
  app/build.gradle
  app/src/main/java/com/boostcamp/dreampicker/App.java
Labels: 리뷰해주세요, 슈퍼심플

#245 issue-243 업로드 이미지 변경
  app/src/main/java/com/boostcamp/dreampicker/extension/databinding/ImageUtil.java
  app/src/main/res/drawable/ic_add_to_photos.xml
Labels: 리뷰해주세요, 슈퍼심플

#247 issue 246 네트워크 유틸 추가
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/java/com/boostcamp/dreampicker/utils/NetworkUtil.java
  app/src/main/res/values/strings.xml
Labels: 리뷰해주세요, 슈퍼심플

#254 [#252] Activity DI 추가
  app/src/main/java/com/boostcamp/dreampicker/di/module/activity/MainModule.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedFragment.java
Labels: 슈퍼심플

#256 issue-255 placeholder 수정 및 레이아웃 최적화
  app/src/main/java/com/boostcamp/dreampicker/extension/databinding/ImageUtil.java
  app/src/main/res/drawable/bg_placeholder_gray.xml
  app/src/main/res/drawable/btn_voted_normal.xml
  app/src/main/res/drawable/btn_voted_selected.xml
  app/src/main/res/drawable/ic_person_gray.xml
  app/src/main/res/drawable/ic_photo.xml
  app/src/main/res/layout/activity_upload.xml
  app/src/main/res/menu/navigation.xml
Labels: 슈퍼심플

#264 issue 238 카카오 비전 API 연동
  app/build.gradle
  app/src/main/java/com/boostcamp/dreampicker/data/model/FeedUploadRequest.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/vision/AdultDetectApi.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/vision/RetrofitClient.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/vision/model/AdultDetectResponse.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/vision/model/Result.java
  app/src/main/java/com/boostcamp/dreampicker/data/repository/FeedRepositoryImpl.java
  app/src/main/java/com/boostcamp/dreampicker/di/module/AppModule.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModel.java
Labels: 리뷰해주세요

#272 issue-269 메인화면 coordinator 레이아웃 적용
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/MainActivity.java
  app/src/main/res/layout/activity_main.xml
Labels: 리뷰해주세요, 슈퍼심플

#273 issue-270 paging sourceLiveData삭제
  app/src/main/java/com/boostcamp/dreampicker/data/paging/MyFeedDataSourceFactory.java
Labels: 리뷰해주세요, 슈퍼심플

#275 issue-274 bottom picker 릭 해결
  app/build.gradle
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/login/LogInActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
  app/src/main/res/values/strings.xml
Labels: 리뷰해주세요, 슈퍼심플

#271 issue-270 프로필 뷰모델 init 함수
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileViewModel.java
  app/src/main/res/layout/layout_profile.xml
Labels: 리뷰해주세요, 슈퍼심플

#281 issue-280 업로드 버그수정
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadActivity.java
Labels: 리뷰해주세요, 슈퍼심플

#279 [#278] 투표 이팩트 두번 문제 해결
  app/build.gradle
  app/src/main/java/com/boostcamp/dreampicker/data/common/FirebaseManager.java
  app/src/main/java/com/boostcamp/dreampicker/data/local/room/entity/VotedFeed.java
  app/src/main/java/com/boostcamp/dreampicker/data/model/Feed.java
  app/src/main/java/com/boostcamp/dreampicker/data/model/User.java
  app/src/main/java/com/boostcamp/dreampicker/data/model/VoteSelectionItem.java
  app/src/main/java/com/boostcamp/dreampicker/data/paging/MyFeedDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/firestore/UserDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/firestore/UserRemoteDataSource.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/firestore/mapper/UserDetailMapper.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/firestore/model/FeedItemRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/data/remote/firestore/model/FeedRemoteData.java
  app/src/main/java/com/boostcamp/dreampicker/di/module/repository/FeedRepositoryModule.java
  app/src/main/java/com/boostcamp/dreampicker/di/scope/ActivityScoped.java
  app/src/main/java/com/boostcamp/dreampicker/di/scope/FragmentScoped.java
  app/src/main/java/com/boostcamp/dreampicker/di/scope/UserId.java
  app/src/main/java/com/boostcamp/dreampicker/extension/common/StringExt.java
  app/src/main/java/com/boostcamp/dreampicker/extension/databinding/ImageUtil.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModel.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/feed/main/FeedViewModelFactory.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/main/login/LogInActivity.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/MyFeedAdapter.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/MyFeedItemViewHolder.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/profile/ProfileFragment.java
  app/src/main/java/com/boostcamp/dreampicker/presentation/upload/UploadViewModelFactory.java
  app/src/main/java/com/boostcamp/dreampicker/utils/MyAppGlideModule.java
  app/src/main/java/com/boostcamp/dreampicker/utils/custom/SelectionGroup.java
  app/src/main/java/com/boostcamp/dreampicker/utils/custom/ShineSelectionGroup.java
Labels: 슈퍼심플
